name: Build Apptainer Image

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: git-runner-tmp   # your local runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show Apptainer version
        run: |
          apptainer --version > output.txt
          ls output.txt
          cat output.txt

      # - name: Build container
      #   run: |
      #     mkdir -p output
      #     apptainer build --fakeroot output/container.sif ubuntu.def

      # - name: Verify container
      #   run: |
      #     apptainer inspect output/container.sif

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: apptainer-image
      #     path: output/container.sif

      - name: Remove full workspace
        run: |
          rm -rf "$GITHUB_WORKSPACE"/*
          rm -rf "$GITHUB_WORKSPACE"/.git

      # - name: cleaning files
      #   uses: actions/checkout@v4
      #   with:
      #     clean: true